version: "3"

services:
  code-server:
    build: .
    ports:
      - "8443:8443"
    volumes:
      - ./workspace:/home/coder/project
    environment:
      - PASSWORD=yourpassword
    container_name: custom-code-server
